cvapp/urls.py
from django.urls import path
from .views import home, login, forgotPass, allProp, allOwner, addProp, addOwner, logout, userProp, payDetails, resetPass, userDoc, newPayment, allFeature, addFeature, allPUpdate, addPUpdate, addStaff, allStaff, assignProp, propInfo

app_name = 'cvapp'

urlpatterns = [
    #auth URL
    path("login/", login, name='login'),
    path("logout/", logout, name='logout'),
    path("forgot_password/", forgotPass, name='fPass'),
    path("reset_password/<str:token>/", resetPass, name='rePass'),
    # path("reset_password/", resetPass, name='rePass'),

    #staff URLs
    path("", home, name='home'),
    path("all-property/", allProp, name='aProp'),
    path("add-property/", addProp, name='addProp'),
    path("add-client/", addOwner, name='addOwner'),
    path("add-staff/", addStaff, name='addStaff'),
    path("home-owners/", allOwner, name='aOwner'),
    path("assign-property/", assignProp, name='assignProp'),
    path("all-staff/", allStaff, name='aStaff'),
    path("add-feature/", addFeature, name='addFeature'),
    path("features/", allFeature, name='allFeature'),
    path("project-update/", allPUpdate, name='allPUpdate'),
    path("add-update/", addPUpdate, name='addPUpdate'),
    path("property-info/<int:id>/", propInfo, name='propInfo'),

    # user URLS
    path("properties/", userProp, name='userProp'),
    path("new-payment/", newPayment, name='newPayment'),
    path("payment/", payDetails, name='payDetails'),
    path("document/", userDoc, name='userDoc'),
]

cve/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cvapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'cvapp.views.error404'
handler500 = 'cvapp.views.error500'

templates/cve_user/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>{{ page }} - CVE </title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <!-- CSS Libraries -->
  <!-- <link rel="stylesheet" href="../node_modules/jqvmap/dist/jqvmap.min.css">
  <link rel="stylesheet" href="../node_modules/summernote/dist/summernote-bs4.css">
  <link rel="stylesheet" href="../node_modules/owl.carousel/dist/assets/owl.carousel.min.css">
  <link rel="stylesheet" href="../node_modules/owl.carousel/dist/assets/owl.theme.default.min.css"> -->
  <link rel="icon" href="{% static '/img/CVE_logo.webp' %}" sizes="32X32">
  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
  <link rel="stylesheet" href="{% static '/css/components.css' %}">
  <link rel="stylesheet" href="{% static '/css/cve.css' %}">
</head>

<body>
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <!-- <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li> -->
          </ul>
          <!-- <div class="search-element">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
            <div class="search-backdrop"></div>
          </div> -->
        </form>
        <ul class="navbar-nav navbar-right">
          <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link nav-link-lg message-toggle"><i class="far fa-envelope"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
              <div class="dropdown-header">Message(s)
                <div class="float-right">
                  <!-- <a href="#">Mark All As Read</a> -->
                </div>
              </div>
              <div class="dropdown-list-content dropdown-list-message">
                <span class="dropdown-item dropdown-item-unread">
                  <div class="dropdown-item-desc">
                    <b>No messages at the moment</b>
                  </div>
                </span>
                <!-- <a href="#" class="dropdown-item dropdown-item-unread">
                  <div class="dropdown-item-avatar">
                    <img alt="image" src="{% static 'img/avatar-2.png' %}" class="rounded-circle">
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Dedik Sugiharto</b>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                    <div class="time">12 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item dropdown-item-unread">
                  <div class="dropdown-item-avatar">
                    <img alt="image" src="{% static 'img/avatar-3.png' %}" class="rounded-circle">
                    <div class="is-online"></div>
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Agung Ardiansyah</b>
                    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    <div class="time">12 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item">
                  <div class="dropdown-item-avatar">
                    <img alt="image" src="{% static 'img/avatar-4.png' %}" class="rounded-circle">
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Ardian Rahardiansyah</b>
                    <p>Duis aute irure dolor in reprehenderit in voluptate velit ess</p>
                    <div class="time">16 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item">
                  <div class="dropdown-item-avatar">
                    <img alt="image" src="{% static 'img/avatar-5.png' %}" class="rounded-circle">
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Alfa Zulkarnain</b>
                    <p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
                    <div class="time">Yesterday</div>
                  </div>
                </a> -->
              </div>
              <!-- <div class="dropdown-footer text-center">
                <a href="#">View All <i class="fas fa-chevron-right"></i></a>
              </div> -->
            </div>
          </li>
          <!-- if there's a notification, add the beep class -->
          <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg"><i class="far fa-bell"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
              <div class="dropdown-header">Notifications
                <!-- <div class="float-right">
                  <a href="#">Mark All As Read</a>
                </div> -->
              </div>
              <div class="dropdown-list-content dropdown-list-icons">
                <!-- <a href="#" class="dropdown-item dropdown-item-unread"> -->
                  <span class="dropdown-item dropdown-item-unread">
                  <!-- <div class="dropdown-item-icon bg-primary text-white">
                    <i class="fas fa-code"></i>
                  </div> -->
                  <div class="dropdown-item-desc">
                    No notifications at the moment
                    <!-- <div class="time text-primary">2 Min Ago</div> -->
                  </div>
                  </span>
                <!-- </a> -->
                <!-- <a href="#" class="dropdown-item">
                  <div class="dropdown-item-icon bg-info text-white">
                    <i class="far fa-user"></i>
                  </div>
                  <div class="dropdown-item-desc">
                    <b>You</b> and <b>Dedik Sugiharto</b> are now friends
                    <div class="time">10 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item">
                  <div class="dropdown-item-icon bg-success text-white">
                    <i class="fas fa-check"></i>
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>
                    <div class="time">12 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item">
                  <div class="dropdown-item-icon bg-danger text-white">
                    <i class="fas fa-exclamation-triangle"></i>
                  </div>
                  <div class="dropdown-item-desc">
                    Low disk space. Let's clean it!
                    <div class="time">17 Hours Ago</div>
                  </div>
                </a> -->
              </div>
              <!-- <div class="dropdown-footer text-center">
                <a href="#">View All <i class="fas fa-chevron-right"></i></a>
              </div> -->
            </div>
          </li>
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <div class="d-sm-none d-lg-inline-block">{{ request.user.first_name  | capfirst }} </div></a>
            <div class="dropdown-menu dropdown-menu-right">
              <a href="#" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Profile
              </a><a href="{% url 'cvapp:newPayment' %}" class="dropdown-item has-icon">
                <i class="fas fa-wallet"></i> New Payment
              </a>
              <!-- <a href="#" class="dropdown-item has-icon">
                <i class="fas fa-bolt"></i> Activities
              </a>
              <a href="#" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Settings
              </a> -->
              <div class="dropdown-divider"></div>
              <a href="{% url 'cvapp:logout' %}" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
            </div>
          </li>
        </ul>
      </nav>
      <div class="main-sidebar">
        <aside id="sidebar-wrapper">
          <div class="sidebar-brand">
            <a href="{% url 'cvapp:home' %}">
              <img src="{% static '/img/CVE_logoo.webp' %}" alt="logo" class="mb-5 mt-2" width="200">
            </a>
          </div>
          <div class="sidebar-brand sidebar-brand-sm">
            <a href="{% url 'cvapp:home' %}"><img src="{% static '/img/CVE_logo.webp' %}" alt="logo" width="45" height="45">
            </a>
          </div>
          <ul class="sidebar-menu" style="margin-top: 20px">
              <li class="menu-header">Your Dashboard</li>
              <li class="nav-item {% if page == 'Dashboard' %}active{% endif %}">
                <a href="{% url 'cvapp:home' %}" class="nav-link"><i class="fas fa-laptop"></i><span>Dashboard</span></a>
              </li>
              <!-- <li class="menu-header"></li> -->
              <li class="nav-item {% if page == 'Properties' %}active{% endif %}">
                <a href="{% url 'cvapp:userProp' %}" class="nav-link"><i class="fas fa-city"></i> <span>My Properties</span></a>
              </li>
              <!-- <li class="menu-header"></li> -->
              <!-- <li class="nav-item {% if page == 'Documents' %}active{% endif %} ">
                <a href="{% url 'cvapp:userDoc' %}" class="nav-link"><i class="fas fa-book"></i> <span>My Documents</span></a>
              </li> -->
              <!-- <li class="menu-header"></li> -->
              <li class="nav-item {% if page == 'Payment History' or page == 'New Payment' %}active{% endif %}">
                <a href="{% url 'cvapp:payDetails' %}" class="nav-link"><i class="fas fa-users-cog"></i> <span>Manage Payments</span></a>
              </li>
            </ul>

            <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
              <a href="https://www.thecitadelviews.com" class="btn btn-cve btn-lg btn-block btn-icon-split">
                <i class="fas fa-globe"></i> Visit Website
              </a>

              
              <div class="card">
                <div class="card-body">
                  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <a href="#"><img class="d-block w-100" src="{% static '/img/cve-mini1.webp' %}" alt="First slide"></a>
                      </div>
                      <div class="carousel-item">
                        <a href="#"><img class="d-block w-100" src="{% static '/img/cve-mini2.webp' %}" alt="Second slide"></a>
                      </div>
                      <div class="carousel-item">
                        <a href="#"><img class="d-block w-100" src="{% static '/img/cve-mini3.webp' %}" alt="Third slide"></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </aside>
      </div>

      <!-- Main Content -->
      {% block content %}


      {% endblock %}
      
      <!-- footer -->
      <footer class="main-footer">
        <div class="footer-left">
          Copyright &copy; 2021 | Citadel View Estate
      </footer>
    </div>
  </div>

  <!-- General JS Scripts -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="{% static 'js/cve.js' %}"></script>

  <!-- JS Libraies -->
  <!-- <script src="../node_modules/jquery-sparkline/jquery.sparkline.min.js"></script>
  <script src="../node_modules/chart.js/dist/Chart.min.js"></script>
  <script src="../node_modules/owl.carousel/dist/owl.carousel.min.js"></script>
  <script src="../node_modules/summernote/dist/summernote-bs4.js"></script>
  <script src="../node_modules/chocolat/dist/js/jquery.chocolat.min.js"></script> -->

  <!-- Template JS File -->
  <script src="{% static 'js/scripts.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

  <!-- Page Specific JS File -->
  <!-- <script src="{% static 'js/page/index.js' %}"></script> -->
  {% block page_js %} {% endblock %}
</body>
</html>