cvapp/urls.py
from django.urls import path
from .views import home, login, forgotPass, allProp, allOwner, addProp, addOwner, logout, userProp, payDetails, resetPass, userDoc, newPayment, allFeature, addFeature, allPUpdate, addPUpdate, addStaff, allStaff, assignProp, propInfo

app_name = 'cvapp'

urlpatterns = [
    #auth URL
    path("login/", login, name='login'),
    path("logout/", logout, name='logout'),
    path("forgot_password/", forgotPass, name='fPass'),
    path("reset_password/<str:token>/", resetPass, name='rePass'),
    # path("reset_password/", resetPass, name='rePass'),

    #staff URLs
    path("", home, name='home'),
    path("all-property/", allProp, name='aProp'),
    path("add-property/", addProp, name='addProp'),
    path("add-client/", addOwner, name='addOwner'),
    path("add-staff/", addStaff, name='addStaff'),
    path("home-owners/", allOwner, name='aOwner'),
    path("assign-property/", assignProp, name='assignProp'),
    path("all-staff/", allStaff, name='aStaff'),
    path("add-feature/", addFeature, name='addFeature'),
    path("features/", allFeature, name='allFeature'),
    path("project-update/", allPUpdate, name='allPUpdate'),
    path("add-update/", addPUpdate, name='addPUpdate'),
    path("property-info/<int:id>/", propInfo, name='propInfo'),

    # user URLS
    path("properties/", userProp, name='userProp'),
    path("new-payment/", newPayment, name='newPayment'),
    path("payment/", payDetails, name='payDetails'),
    path("document/", userDoc, name='userDoc'),
]

cve/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cvapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'cvapp.views.error404'
handler500 = 'cvapp.views.error500'

templates/user/add-feature.html
{% extends 'user/base/base.html' %}

{% block content %}
{% load static %}

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <div class="section-header-back">
              <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Add new feature</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active"><a href="{% url 'cvapp:home' %}">Dashboard</a></div>
              <div class="breadcrumb-item active"><a href="{% url 'cvapp:allFeature' %}">Features</a></div>
              <div class="breadcrumb-item">New Feature</div>
            </div>
          </div>

          <div class="section-body">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-body">
                    
                    {% if messages %}
                      {% for message in messages %}
                        <div class="alert alert-warning text-center" role="alert">
                          <b>{{ message }}</b>
                        </div>
                      {% endfor %}
                    {% elif passa %}
                      <div class="alert alert-success text-center" role="alert">
                        <b>{{ passa }}</b>
                      </div>
                    {% endif %}
                    
                    <form action="{% url 'cvapp:addFeature' %}" method="POST" class="wizard-content mt-2 needs-validation" novalidate="" enctype="multipart/form-data">
                      {% csrf_token %}
                      <div class="wizard-pane">
                        <div class="form-group row align-items-center">
                          <label class="col-md-4 text-md-right text-left">Title</label>
                          <div class="col-lg-4 col-md-6">
                            <input type="text" name="title" class="form-control" required placeholder="Title of the feature">
                            <div class="invalid-feedback">
                              Please enter a title
                            </div>
                          </div>
                        </div>
                        <div class="form-group row align-items-center">
                          <label class="col-md-4 text-md-right text-left">Link</label>
                          <div class="col-lg-4 col-md-6">
                            <input type="URL" name="page_link" class="form-control" required placeholder="Link to website. Include protocol">
                            <div class="invalid-feedback">
                              Please enter the <b>complete path to the landing page </b>including the protocol https://
                            </div>
                          </div>
                        </div>
                        <div class="form-group row align-items-center">
                          <label class="col-md-4 text-md-right text-left">Expiry Date</label>
                          <div class="col-lg-4 col-md-6">
                            <input type="date" name="date" class="form-control" required="">
                            <div class="invalid-feedback">
                              Please enter a proper date
                            </div>
                          </div>
                        </div>
                        <div class="form-group row">
                          <label class="col-md-4 text-md-right text-left mt-2">Upload Image</label>
                          <div class="col-sm-12 col-md-7">
                              <input type="file" name="feature_image" accept="image/*" required/>
                              <div class="invalid-feedback">
                                No image selected
                              </div>
                              <small id="roleBlock" class="form-text text-muted">
                                Image should be a perfect square and less than 500kb
                              </small>
                          </div>
                        </div>
                        <div class="form-group row">
                          <div class="col-md-4"></div>
                          <div class="col-lg-4 col-md-6 text-right">
                            <button type="submit" name="formSubmit" class="btn btn-icon icon-right btn-primary">
                              Upload&nbsp;<i class="fas fa-upload"></i>
                            </button>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      {% endblock %}

      {% block page_js %} 
        <!-- Page Specific JS File -->
      {% endblock %}
      

templates/user/add-home-owner.html
{% extends 'user/base/base.html' %}

{% block content %}
{% load static %}

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <div class="section-header-back">
              <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Add Client</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active"><a href="{% url 'cvapp:home' %}">Dashboard</a></div>
              <div class="breadcrumb-item"><a href="{% url 'cvapp:aOwner' %}">Clients</a></div>
              <div class="breadcrumb-item">Add home owner</div>
            </div>
          </div>

          <div class="section-body">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-body">
                    <div class="row mt-4">
                      <div class="col-12 col-lg-8 offset-lg-2">
                        <div class="wizard-steps">
                          <div class="wizard-step wizard-step-active">
                            <div class="wizard-step-icon">
                              <i class="far fa-user"></i>
                            </div>
                            <div class="wizard-step-label">
                              New Home Owner
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {% if messages %}
                      {% for message in messages %}
                        <div class="alert alert-warning text-center" role="alert">
                          <b>{{ message }}</b>
                        </div>
                      {% endfor %}
                    {% elif passa %}
                      <div class="alert alert-success text-center" role="alert">
                        User has successfully being created. The user's password is <b>{{ passa }}</b>
                      </div>
                    {% endif %}
                    
                    <form action="{% url 'cvapp:addOwner' %}" method="POST" class="wizard-content mt-2 needs-validation" novalidate="">
                      {% csrf_token %}
                      <div class="wizard-pane">
                        <div class="form-group row align-items-center">
                          <label for="firstname" class="col-md-4 text-md-right text-left">First Name</label>
                          <div class="col-lg-4 col-md-6">
                            <input id="firstname" type="text" name="firstname" class="form-control" value='{{ first_name }}' required autofocus>
                            <div class="invalid-feedback">
                              Please enter a first name
                            </div>
                          </div>
                        </div>
                        <div class="form-group row align-items-center">
                          <label class="col-md-4 text-md-right text-left">Last Name</label>
                          <div class="col-lg-4 col-md-6">
                            <input type="text" name="lastname" class="form-control" value='{{ last_name }}' required="">
                            <div class="invalid-feedback">
                              Please enter a last name
                            </div>
                          </div>
                        </div>
                        <div class="form-group row align-items-center">
                          <label class="col-md-4 text-md-right text-left">Default Password</label>
                          <div class="col-lg-4 col-md-6">
                            <input type="Password" name="password" class="form-control" required="">
                            <div class="invalid-feedback">
                              Please enter a default password
                            </div>
                            <small id="roleBlock" class="form-text text-muted">
                              This is a unique<b> password</b> for the home owner that can only be used once.
                            </small>
                          </div>
                        </div>
                        <div class="form-group row align-items-center">
                          <label class="col-md-4 text-md-right text-left">Email</label>
                          <div class="col-lg-4 col-md-6">
                            <input type="email" name="email" class="form-control" value='{{ email }}' required>
                            <div class="invalid-feedback">
                              Please enter an email address
                            </div>
                          </div>
                        </div>
                        <div class="form-group row align-items-center">
                          <label class="col-md-4 text-md-right text-left">Phone Number</label>
                          <div class="col-lg-4 col-md-6">
                            <input type="tel" name="phoneNumber" class="form-control" value='{{ phone_number }}' required="required">
                            <div class="invalid-feedback">
                              Please enter a correct phone format
                            </div>
                            <small id="roleBlock" class="form-text text-muted">
                              Please enter the phone number in the format<b> +234-0000000000</b>.
                            </small>
                          </div>
                        </div>
                        <!-- <div class="form-group row">
                          <label class="col-md-4 text-md-right text-left mt-2">Client Photo</label>
                          <div class="col-sm-12 col-md-7">
                            <div id="image-preview" class="image-preview">
                              <label for="image-upload" id="image-label">Choose Picture</label>
                              <input type="file" name="image" id="image-upload"/>
                            </div>
                          </div>
                        </div> -->
                        <div class="form-group row">
                          <div class="col-md-4"></div>
                          <div class="col-lg-4 col-md-6 text-right">
                            <button type="submit" name="formSubmit" class="btn btn-icon icon-right btn-primary">
                              Submit<i class="fas fa-arrow-right"></i>
                            </button>
                            <!-- <a href="{% url 'cvapp:addOwner' %}" class="btn btn-icon icon-right btn-primary">Submit<i class="fas fa-arrow-right"></i></a> -->
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      {% endblock %}

      {% block page_js %} 
        <!-- Page Specific JS File -->
      {% endblock %}
      

templates/user/add-project-update.html
{% extends 'user/base/base.html' %}

{% block content %}
{% load static %}

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <div class="section-header-back">
              <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Add new update</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active"><a href="{% url 'cvapp:home' %}">Dashboard</a></div>
              <div class="breadcrumb-item active"><a href="{% url 'cvapp:allPUpdate' %}">Project Update</a></div>
              <div class="breadcrumb-item">New Feature</div>
            </div>
          </div>

          <div class="section-body">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-body">
                    
                    {% if messages %}
                      {% for message in messages %}
                        <div class="alert alert-warning text-center" role="alert">
                          <b>{{ message }}</b>
                        </div>
                      {% endfor %}
                    {% elif success %}
                      <div class="alert alert-success text-center" role="alert">
                        <b>{{ success }}</b>
                      </div>
                    {% endif %}
                    
                    <form action="{% url 'cvapp:addPUpdate' %}" method="POST" class="wizard-content mt-2 needs-validation" novalidate="" enctype="multipart/form-data">
                      {% csrf_token %}
                      <div class="wizard-pane">
                        <div class="form-group row align-items-center">
                          <label class="col-md-4 text-md-right text-left">Description</label>
                          <div class="col-lg-6 col-md-6">
                            <textarea name="description" class="form-control  summernote-simple" required></textarea>
                            <div class="invalid-feedback">
                              Please enter a description that will be displayed to home owners
                            </div>
                          </div>
                        </div>
                        
                        <div class="form-group row align-items-center">
                          <label class="col-md-4 text-md-right text-left">Update Date</label>
                          <div class="col-lg-4 col-md-6">
                            <input type="date" name="date" class="form-control" required>
                            <div class="invalid-feedback">
                              Please enter a proper date
                            </div>
                          </div>
                        </div>
                        <div class="form-group row">
                          <label class="col-md-4 text-md-right text-left mt-2">Upload Image(s)</label>
                          <div class="col-sm-12 col-md-7">
                              <input type="file" name="feature_image" accept="image/*" multiple/>
                              <div class="invalid-feedback">
                                No image selected
                              </div>
                              <small id="roleBlock" class="form-text text-muted">
                                Optional
                              </small>
                          </div>
                        </div>
                        <div class="form-group row">
                          <div class="col-md-4"></div>
                          <div class="col-lg-6 col-md-6 text-right">
                            <button type="submit" name="formSubmit" class="btn btn-icon icon-right btn-primary">
                              Add&nbsp;Update<i class="fas fa-arrow-right"></i>
                            </button>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      {% endblock %}

      {% block page_js %} 
        <!-- Page Specific JS File -->
        <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
      {% endblock %}
      

templates/user/property-info.html
{% extends 'user/base/base.html' %}

{% block content %}
{% load static %}
{% load humanize %}
{% load convert %}
      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <div class="section-header-back">
              <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Property details</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active"><a href="{% url 'cvapp:home' %}">Dashboard</a></div>
              <div class="breadcrumb-item active"><a href="{% url 'cvapp:aProp' %}">All Properties</a></div>
              <div class="breadcrumb-item"> Property Info</div>
            </div>
          </div>

          <div class="section-body">
            <h2 class="section-title"></h2>
            <p class="section-lead">View and edit the property information below
            </p>

            <div id="output-status"></div>
            <hr>
            {% if house %}
            <div class="row">
              <div class="col-md-5">
                <div class="card card-warning">
                  <div class="card-header">
                    <h4>{{ house.title | capfirst }}</h4>
                    <div class="card-header-action">
                      <span title="Purchase price">&#8358;{{ house.cost | intcomma }}</span>
                    </div>
                  </div>
                  <div class="card-body">
                    <div class="chocolat-parent">
                      <!-- <a href="{% static '/img/login-bg1.jpg' %}" title="Just an example"> -->
                        <div data-crop-image="">
                          <img alt="{{ house.title }}" src="{{ house.images.url }}" class="img-fluid">
                        </div>
                      <!-- </a> -->
                    </div>
                    <div class="mt-2 mb-2"><b>Quantity: </b>{{ house.quantity }}<div class="bullet"></div><div class="bullet"></div><b>Qty Assigned: </b>{{ assigned_count }}<div class="bullet"></div><div class="bullet"></div><b>Added By: </b>{{ house.created_by }}</div>
                    <div class="mt-2 text-muted">
                      <div class="progress mt-2 mb-1">
                        <div class="progress-bar bg-cve" role="progressbar" data-width="{{ house.progress }}%" aria-valuenow="{{ house.progress }}" aria-valuemin="0" aria-valuemax="100">{{ house.progress }}%</div>
                      </div>
                    </div>
                    <hr>
                    <p>{{ house.desription }}</p>
                  </div>
                  <div class="card-footer bg-whitesmoke">
                    <span class="card-link"><strong>Created on: </strong>{{ house.date_created | date }}</span>
                  </div>
                </div>
              </div>
              <div class="col-md-7">
                {% if messages %}
                  {% for message in messages %}
                    <div class="alert alert-warning text-center" role="alert">
                      <b>{{ message }}</b>
                    </div>
                  {% endfor %}
                {% elif success %}
                  <div class="alert alert-success text-center" role="alert">
                    {{ success }}
                  </div>
                {% endif %}
                <form id="setting-form" action="{% url 'cvapp:propInfo' id=house.house_id %}" method="POST" class="wizard-content mt-2 needs-validation" novalidate="" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="card" id="settings-card">
                    <div class="card-header">
                      <h4>Edit Property</h4>
                    </div>
                    <div class="card-body">
                      <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"> Title</label>
                        <div class="col-sm-6 col-md-9">
                          <input type="text" name="title" class="form-control" id="site-title" required value="{%if title %}{{ title }}{% else %}{{ house.title }}{% endif %}">
                          <div class="invalid-feedback">
                            Please enter a title
                          </div>
                        </div>
                      </div>
                      <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"> Quantity</label>
                        <div class="col-sm-6 col-md-9">
                          <input type="number" name="quantity" class="form-control" required min="1"  oninput="this.value = 
                            !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null" value="{%if quantity %}{{ quantity}}{% else %}{{ house.quantity }}{% endif %}">
                          <div class="invalid-feedback">
                            Please enter a valid number
                          </div>
                        </div>
                      </div>
                      
                      <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"> Progress</label>
                        <div class="col-sm-6 col-md-9">
                          <input type="number" name="progress" class="form-control" required="" min="0" max="100" oninput="this.value = 
                            !!this.value && Math.abs(this.value) >= 0 &&Math.abs(this.value) <= 100 ? Math.abs(this.value) : null" value="{%if progress %}{{ progress }}{% else %}{{ house.progress }}{% endif %}">
                          <div class="invalid-feedback">
                            Please enter a valid number less than 100
                          </div>
                          <small id="roleBlock" class="form-text text-muted">
                            Please enter the construction progress
                          </small>
                        </div>
                      </div>
                      <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"> Selling Price</label>
                        <div class="col-sm-6 col-md-9">
                          <div class="input-group mb-3">
                            <div class="input-group-prepend">
                              <span class="input-group-text">&#8358;</span>
                            </div>
                            <input type="number" name="cost" class="form-control" min="0"  step="0.01" oninput="this.value = 
                            !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null" value="{%if cost %}{{ cost|floatformat:-2 }}{% else %}{{ house.cost|floatformat:-2 }}{% endif %}">
                            <div class="invalid-feedback">
                              Please enter a valid selling price in 2 decimal places
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="form-group row align-items-center">
                        <label for="site-description" class="form-control-label col-sm-3 text-md-right">Description</label>
                        <div class="col-sm-6 col-md-9">
                          <textarea class="form-control" name="description" id="description">{%if description %}{{ description }}{% else %}{{ house.desription }}{% endif %}</textarea>
                        </div>
                      </div>
                      <div class="form-group row align-items-center">
                        <label class="form-control-label col-sm-3 text-md-right">Property Photo</label>
                        <div class="col-sm-6 col-md-9">
                          <div class="custom-file">
                            <input type="file" name="prop_image" class="custom-file-input" accept="image/*">
                            <label class="custom-file-label">Choose File</label>
                          </div>
                          <div class="form-text text-muted">The image must have a maximum size of 50kb</div>
                        </div>
                      </div>
                    </div>
                    <div class="card-footer bg-whitesmoke text-md-right">
                      <button class="btn btn-primary" id="save-btn">Save Changes</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Assignees</h4>
                  </div>
                  <div class="card-body p-0">
                    <div class="table-responsive">
                      <table class="table table-striped">
                        <tr>
                          <th>Home Owner</th>
                          <th>Date Assigned</th>
                          <th>Added By</th>
                          <th></th>
                        </tr>
                        {% for assigned in assigned_to %}
                        <tr>
                          <td><a href="#">{{ assigned.user_id}}</a></td>
                          <td class="font-weight-600">{{ assigned.date_created|date}}</td>
                          <td>{{ assigned.created_by}}</td><td><a href="#" class="btn btn-cve">Delete</a></td>
                        </tr>
                        {% empty %}
                        <tr>
                          <td colspan="3" class="text-center"><b> This property is yet to be assigned. Assign <a href="{% url 'cvapp:assignProp' %}"> property</a> now.</b></td>
                        </tr>
                        {% endfor %}
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}
  		    </div>
      	</section>
      </div>
      {% endblock %}

       